- project:
    check:
      jobs:
        - congress-devstack-api-mysql
        - congress-pe-replicated-mysql
        - congress-devstack-py35-api-mysql
    gate:
      jobs:
        - congress-devstack-api-mysql
        - congress-pe-replicated-mysql
        - congress-devstack-py35-api-mysql

